feat: redirect to up to date spec
ceramicnetwork/ceramic pull request #247
Opened 2023-02-21 19:38 UTC by zachferland

2023-02-22 13:31 UTC, oed requested changes
We should remove all text here to avoid confusion and only have one big redirect link.

2023-02-22 15:54 UTC, zachferland commented
@oed ok, im good with that, could also make this link a lot bigger if we wanted to keep content for any reason or move it to another md file

2023-02-22 17:34 UTC, zachferland commented
Made it larger, removed content from specification, moved to legacy_specification file just for reference

2023-02-23 11:41 UTC, oed approved these changes

2023-02-23 20:06 UTC, merged